// Vector Store — local embeddings with cosine similarity
// Uses pre-computed knowledge chunks from PDF extraction or static knowledge base
import type { KnowledgeChunk } from './types';

// --- Cosine Similarity ---
function cosineSimilarity(a: number[], b: number[]): number {
    if (a.length !== b.length) return 0;
    let dotProduct = 0;
    let normA = 0;
    let normB = 0;
    for (let i = 0; i < a.length; i++) {
        dotProduct += a[i] * b[i];
        normA += a[i] * a[i];
        normB += b[i] * b[i];
    }
    const denominator = Math.sqrt(normA) * Math.sqrt(normB);
    return denominator === 0 ? 0 : dotProduct / denominator;
}

// --- Simple TF-IDF-like Embeddings (lightweight, no ML model needed) ---
// This creates bag-of-words style vectors for keyword matching
function tokenize(text: string): string[] {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, ' ')
        .split(/\s+/)
        .filter(w => w.length > 2);
}

// Build vocabulary from all chunks
let vocabulary: string[] = [];
let vocabIndex: Map<string, number> = new Map();

function buildVocabulary(chunks: KnowledgeChunk[]): void {
    const wordSet = new Set<string>();
    for (const chunk of chunks) {
        const words = tokenize(`${chunk.title} ${chunk.content} ${chunk.keywords.join(' ')}`);
        words.forEach(w => wordSet.add(w));
    }
    vocabulary = Array.from(wordSet);
    vocabIndex = new Map(vocabulary.map((w, i) => [w, i]));
}

function textToVector(text: string): number[] {
    const tokens = tokenize(text);
    const vector = new Array(vocabulary.length).fill(0);
    const tokenCounts = new Map<string, number>();

    for (const token of tokens) {
        tokenCounts.set(token, (tokenCounts.get(token) || 0) + 1);
    }

    for (const [token, count] of tokenCounts) {
        const idx = vocabIndex.get(token);
        if (idx !== undefined) {
            // TF: term frequency normalized
            vector[idx] = count / tokens.length;
        }
    }

    return vector;
}

// --- Knowledge Base (static, curated content) ---
const knowledgeBase: KnowledgeChunk[] = [
    // Machine Learning
    { id: 'ml-1', subject: 'Machine Learning', module: 'Supervised Learning', topic: 'Linear Regression', title: 'Linear Regression Fundamentals', content: 'Linear regression is a supervised learning algorithm that models the linear relationship between a dependent variable and one or more independent variables. The model predicts continuous values using the equation y = wx + b, where w is the weight (slope) and b is the bias (intercept). The cost function used is Mean Squared Error (MSE), which measures the average squared difference between predicted and actual values. Gradient descent is used to minimize the MSE by iteratively adjusting weights. Regularization techniques like Ridge (L2) and Lasso (L1) help prevent overfitting by adding penalty terms to the cost function.', keywords: ['linear regression', 'mse', 'gradient descent', 'ridge', 'lasso', 'regularization', 'supervised'], pageRef: 'ML.pdf p.1-5' },
    { id: 'ml-2', subject: 'Machine Learning', module: 'Supervised Learning', topic: 'Logistic Regression', title: 'Logistic Regression and Classification', content: 'Logistic regression is a classification algorithm that uses the sigmoid function σ(x) = 1/(1+e^-x) to map outputs to probabilities between 0 and 1. For binary classification, a threshold (usually 0.5) determines the class label. The cost function is binary cross-entropy: -[y·log(ŷ) + (1-y)·log(1-ŷ)], which is convex and suitable for gradient descent. For multi-class problems, softmax regression extends logistic regression using the softmax function. Decision boundaries are linear in feature space, making it a linear classifier despite the non-linear sigmoid transformation.', keywords: ['logistic regression', 'sigmoid', 'classification', 'cross-entropy', 'softmax', 'binary'], pageRef: 'ML.pdf p.6-10' },
    { id: 'ml-3', subject: 'Machine Learning', module: 'Supervised Learning', topic: 'Decision Trees', title: 'Decision Trees and Splitting Criteria', content: 'Decision trees partition feature space by learning simple decision rules from data. ID3 algorithm uses Information Gain (entropy reduction) for splitting, while CART uses Gini Impurity. Entropy H(S) = -Σp_i·log2(p_i) measures disorder. Gini Index = 1 - Σp_i² measures probability of misclassification. Trees are prone to overfitting, which is addressed by pruning (pre-pruning: max depth, min samples; post-pruning: cost-complexity pruning). Advantages include interpretability and no need for feature scaling. Disadvantages include instability and tendency to overfit.', keywords: ['decision tree', 'entropy', 'gini', 'information gain', 'pruning', 'id3', 'cart'], pageRef: 'ML.pdf p.11-18' },
    { id: 'ml-4', subject: 'Machine Learning', module: 'Supervised Learning', topic: 'Support Vector Machines', title: 'SVM and Kernel Methods', content: 'Support Vector Machines find the maximum margin hyperplane that separates classes. The margin is 2/||w||, where w is the weight vector. Support vectors are the closest data points to the hyperplane. For non-linearly separable data, the kernel trick maps data to higher-dimensional space: Linear K(x,y) = x·y, Polynomial K(x,y) = (x·y + c)^d, RBF/Gaussian K(x,y) = exp(-γ||x-y||²). Soft margin SVM uses slack variables ξ for misclassification tolerance, controlled by parameter C. Larger C = harder margin, smaller C = softer margin.', keywords: ['svm', 'support vector', 'kernel', 'margin', 'hyperplane', 'rbf', 'gaussian'], pageRef: 'ML.pdf p.19-25' },
    { id: 'ml-5', subject: 'Machine Learning', module: 'Supervised Learning', topic: 'Random Forest', title: 'Ensemble Methods: Random Forest and Bagging', content: 'Random Forest is an ensemble method using bagging (Bootstrap Aggregating) with random feature subsets. It builds multiple decision trees on bootstrapped samples, each considering √p features at each split (for classification) or p/3 (for regression). Predictions are aggregated via majority voting (classification) or averaging (regression). This reduces variance and overfitting compared to single trees. Out-of-Bag (OOB) error provides an unbiased estimate without separate validation set. Feature importance is measured by mean decrease in impurity or permutation importance.', keywords: ['random forest', 'bagging', 'ensemble', 'bootstrap', 'feature importance', 'oob'], pageRef: 'ML.pdf p.26-32' },
    { id: 'ml-6', subject: 'Machine Learning', module: 'Unsupervised Learning', topic: 'K-Means Clustering', title: 'K-Means Clustering Algorithm', content: 'K-Means is an iterative clustering algorithm: 1) Initialize K centroids, 2) Assign each point to nearest centroid, 3) Update centroids to cluster means, 4) Repeat until convergence. The objective is to minimize within-cluster sum of squares (WCSS). Elbow method helps choose K by plotting WCSS vs K. K-Means++ initialization improves convergence by spreading initial centroids. Limitations: assumes spherical clusters, sensitive to outliers, requires K upfront, may converge to local optima. Alternatives: K-Medoids (uses actual points as centers), DBSCAN (density-based, no K needed).', keywords: ['kmeans', 'clustering', 'centroid', 'wcss', 'elbow', 'unsupervised'], pageRef: 'ML.pdf p.33-38' },
    { id: 'ml-7', subject: 'Machine Learning', module: 'Unsupervised Learning', topic: 'PCA', title: 'Principal Component Analysis', content: 'PCA is a dimensionality reduction technique that finds orthogonal directions of maximum variance. Steps: 1) Standardize data, 2) Compute covariance matrix, 3) Calculate eigenvalues and eigenvectors, 4) Select top-k components, 5) Project data. The explained variance ratio indicates how much information each component retains. PCA is useful for visualization (2D/3D projection), noise reduction, and preprocessing for ML algorithms. Limitations: linear only, components may not be interpretable, sensitive to scaling. Kernel PCA handles non-linear relationships using kernel functions.', keywords: ['pca', 'dimensionality reduction', 'eigenvalue', 'eigenvector', 'covariance', 'variance'], pageRef: 'ML.pdf p.39-44' },
    { id: 'ml-8', subject: 'Machine Learning', module: 'Deep Learning', topic: 'Neural Networks', title: 'Neural Networks and Backpropagation', content: 'Neural networks consist of layers of interconnected neurons. Each neuron computes z = Σ(wi·xi) + b, then applies an activation function a = f(z). Common activations: ReLU max(0,x) — fast, avoids vanishing gradients; Sigmoid 1/(1+e^-x) — squashes to (0,1); Tanh — squashes to (-1,1). Backpropagation computes gradients using chain rule ∂L/∂w = ∂L/∂a · ∂a/∂z · ∂z/∂w. Optimizers like SGD, Adam, RMSprop update weights. Regularization: Dropout randomly deactivates neurons, L2/L1 penalties, Batch Normalization normalizes activations.', keywords: ['neural network', 'backpropagation', 'relu', 'sigmoid', 'dropout', 'adam', 'gradient'], pageRef: 'ML.pdf p.45-55' },
    { id: 'ml-9', subject: 'Machine Learning', module: 'Deep Learning', topic: 'CNNs', title: 'Convolutional Neural Networks', content: 'CNNs use convolutional layers for spatial feature extraction. A convolution applies learnable filters to input, producing feature maps. Output size = (Input - Filter + 2·Padding)/Stride + 1. Pooling layers (Max/Average) reduce spatial dimensions and add translation invariance. Common architectures: LeNet-5, AlexNet, VGG (deep, 3×3 filters), ResNet (skip connections solve vanishing gradients), Inception (parallel multi-scale convolutions). Applications: image classification, object detection (YOLO, R-CNN), segmentation, transfer learning using pretrained models like ImageNet.', keywords: ['cnn', 'convolution', 'pooling', 'resnet', 'filter', 'feature map', 'stride'], pageRef: 'ML.pdf p.56-65' },
    { id: 'ml-10', subject: 'Machine Learning', module: 'Deep Learning', topic: 'Transformers', title: 'Transformer Architecture and Attention', content: 'Transformers use self-attention to process sequences in parallel. Self-attention: Attention(Q,K,V) = softmax(QK^T/√d_k)V, where Q, K, V are linear projections of input. Multi-head attention runs h parallel attention heads for diverse representations. Architecture: Encoder (self-attention + FFN × N layers) and Decoder (masked self-attention + cross-attention + FFN × N layers). Positional encoding adds position information since Transformers lack recurrence. Key models: BERT (encoder-only, bidirectional), GPT (decoder-only, autoregressive). Advantages: parallelizable, captures long-range dependencies.', keywords: ['transformer', 'self-attention', 'multi-head', 'bert', 'gpt', 'positional encoding', 'attention'], pageRef: 'ML.pdf p.66-75' },
    { id: 'ml-11', subject: 'Machine Learning', module: 'Model Evaluation', topic: 'Cross Validation', title: 'Model Validation Techniques', content: 'Cross-validation provides robust model evaluation. K-fold CV splits data into K folds, training on K-1 and testing on 1, rotating K times. Stratified K-fold preserves class proportions. Leave-One-Out (LOOCV) uses K=N — unbiased but expensive. Hold-out validation (train/val/test split, e.g., 70/15/15) is simplest. Nested CV uses outer loop for evaluation and inner loop for hyperparameter tuning. Metrics: Accuracy, Precision, Recall, F1-Score, AUC-ROC, Log Loss. Confusion matrix visualizes TP, TN, FP, FN.', keywords: ['cross-validation', 'k-fold', 'stratified', 'confusion matrix', 'auc', 'roc'], pageRef: 'ML.pdf p.76-82' },
    { id: 'ml-12', subject: 'Machine Learning', module: 'Model Evaluation', topic: 'Bias-Variance Tradeoff', title: 'Bias-Variance Tradeoff and Regularization', content: 'Total Error = Bias² + Variance + Irreducible Error. High bias (underfitting): model too simple, misses patterns, high training error. High variance (overfitting): model too complex, memorizes noise, low training but high test error. Regularization reduces variance: L1 (Lasso) adds |w| penalty and produces sparse models; L2 (Ridge) adds w² penalty and shrinks all weights. Learning curves plot training/validation error vs training set size — diagnose underfitting (gap between) vs overfitting (divergence). Solutions: more data, feature engineering, regularization, simpler model.', keywords: ['bias', 'variance', 'underfitting', 'overfitting', 'regularization', 'learning curve'], pageRef: 'ML.pdf p.83-90' },
    // DSA
    { id: 'dsa-1', subject: 'Data Structures & Algorithms', module: 'Arrays & Strings', topic: 'Array Operations', title: 'Arrays: Operations and Complexity', content: 'Arrays store elements in contiguous memory locations, enabling O(1) random access by index. Insertion at end is O(1) (amortized for dynamic arrays), at beginning or middle is O(n) due to shifting. Deletion is O(n) for similar reasons. Linear search is O(n), binary search on sorted arrays is O(log n). Two-pointer technique efficiently solves problems on sorted arrays. Kadane algorithm finds maximum subarray sum in O(n). Dutch National Flag algorithm sorts arrays with 3 distinct values in O(n). Common patterns: prefix sums for range queries, difference arrays for range updates.', keywords: ['array', 'access', 'insertion', 'binary search', 'kadane', 'prefix sum', 'two pointer'], pageRef: 'DSA.pdf p.1-10' },
    { id: 'dsa-2', subject: 'Data Structures & Algorithms', module: 'Arrays & Strings', topic: 'String Manipulation', title: 'String Algorithms and Pattern Matching', content: 'Strings are sequences of characters. Common operations: concatenation O(m+n), substring O(n), comparison O(n). Pattern matching algorithms: Brute force O(nm), KMP (Knuth-Morris-Pratt) O(n+m) using failure function/prefix table, Rabin-Karp O(n+m) average using rolling hash. String processing: palindrome check using two pointers, anagram detection using character frequency arrays. Trie data structure enables prefix-based operations. Suffix arrays sort all suffixes for efficient pattern matching. Important: immutability in many languages — use StringBuilder for O(n) vs O(n²) concatenation.', keywords: ['string', 'pattern matching', 'kmp', 'rabin-karp', 'trie', 'palindrome', 'anagram'], pageRef: 'DSA.pdf p.11-18' },
    { id: 'dsa-3', subject: 'Data Structures & Algorithms', module: 'Arrays & Strings', topic: 'Sliding Window', title: 'Sliding Window Technique', content: 'Sliding window maintains a window [left, right] over the array, expanding right to include elements and contracting left to maintain invariants. Fixed-size window: compute initial window sum, then slide by removing leftmost and adding rightmost element. Variable-size window: expand right until condition breaks, then contract left. Classic problems: maximum sum subarray of size k, longest substring without repeating characters, minimum window substring, smallest subarray with sum ≥ target. Reduces O(n²) or O(n³) brute force to O(n). Often combined with hash maps for frequency tracking.', keywords: ['sliding window', 'two pointer', 'subarray', 'substring', 'window sum', 'variable size'], pageRef: 'DSA.pdf p.19-25' },
    { id: 'dsa-4', subject: 'Data Structures & Algorithms', module: 'Trees & Graphs', topic: 'Binary Trees', title: 'Binary Trees: Traversal and Properties', content: 'Binary trees have nodes with at most 2 children. Types: Full (every node has 0 or 2 children), Complete (all levels full except last, filled left to right), Perfect (all internal nodes have 2 children, all leaves at same level), Balanced (height diff of subtrees ≤ 1). Traversals: Inorder (Left-Node-Right, gives sorted order for BST), Preorder (Node-Left-Right, for serialization), Postorder (Left-Right-Node, for deletion), Level-order (BFS using queue). Properties: max nodes at level i = 2^i, max nodes with height h = 2^(h+1)-1, height of complete tree = floor(log₂n).', keywords: ['binary tree', 'traversal', 'inorder', 'preorder', 'postorder', 'balanced', 'complete'], pageRef: 'DSA.pdf p.26-35' },
    { id: 'dsa-5', subject: 'Data Structures & Algorithms', module: 'Trees & Graphs', topic: 'BST', title: 'Binary Search Trees', content: 'BST property: all left subtree values < node value < all right subtree values. Operations: Search O(h), Insert O(h), Delete O(h) where h is height. Deletion cases: leaf (remove), one child (replace with child), two children (replace with inorder successor/predecessor). Balanced BSTs maintain h = O(log n): AVL Trees (strict balance, rotations after each insert/delete), Red-Black Trees (relaxed balance, fewer rotations, used in STL map/Java TreeMap). Inorder traversal gives sorted sequence. Finding kth smallest element: augmented BST with subtree sizes.', keywords: ['bst', 'binary search tree', 'avl', 'red-black', 'rotation', 'balanced', 'search'], pageRef: 'DSA.pdf p.36-43' },
    { id: 'dsa-6', subject: 'Data Structures & Algorithms', module: 'Trees & Graphs', topic: 'Graph Traversal', title: 'Graph Traversal: BFS and DFS', content: 'Graphs G=(V,E) can be directed/undirected, weighted/unweighted. Representations: adjacency matrix O(V²) space — good for dense graphs; adjacency list O(V+E) space — good for sparse graphs. BFS: uses queue, explores level by level, finds shortest path in unweighted graphs, O(V+E). DFS: uses stack/recursion, explores depth-first, useful for topological sort, cycle detection, connected components, O(V+E). Applications: BFS — shortest path, level-order traversal, detecting bipartite; DFS — topological sort, SCC (Tarjan/Kosaraju), detecting back edges (cycles), articulation points and bridges.', keywords: ['graph', 'bfs', 'dfs', 'traversal', 'adjacency list', 'adjacency matrix', 'topological'], pageRef: 'DSA.pdf p.44-55' },
    { id: 'dsa-7', subject: 'Data Structures & Algorithms', module: 'Trees & Graphs', topic: 'Shortest Path', title: 'Shortest Path Algorithms', content: 'Dijkstra: greedy, non-negative weights, O((V+E)log V) with min-heap. Process: extract minimum distance vertex, relax all neighbors. Fails with negative edges. Bellman-Ford: handles negative weights, detects negative cycles, O(VE). Relaxes all edges V-1 times; if Vth iteration still relaxes, negative cycle exists. Floyd-Warshall: all-pairs shortest path, O(V³), uses DP: dp[i][j] = min(dp[i][j], dp[i][k]+dp[k][j]). A*: heuristic-guided, f(n) = g(n) + h(n), finds optimal path faster than Dijkstra for grids. MST: Kruskal (sort edges, union-find), Prim (grow tree from vertex).', keywords: ['dijkstra', 'bellman-ford', 'floyd-warshall', 'shortest path', 'negative cycle', 'mst', 'prim', 'kruskal'], pageRef: 'DSA.pdf p.56-65' },
    { id: 'dsa-8', subject: 'Data Structures & Algorithms', module: 'Dynamic Programming', topic: '1D DP', title: 'Dynamic Programming: 1D Problems', content: 'DP solves problems with overlapping subproblems and optimal substructure. Two approaches: Top-down (memoization with recursion) and Bottom-up (tabulation with iteration). Classic 1D problems: Fibonacci (dp[i] = dp[i-1]+dp[i-2]) O(n), Climbing Stairs (same recurrence), Coin Change (dp[i] = min(dp[i-coin]+1) for all coins), Longest Increasing Subsequence (dp[i] = max(dp[j]+1) for j<i where a[j]<a[i]) O(n²) or O(n log n) with binary search, House Robber (dp[i] = max(dp[i-1], dp[i-2]+val[i])), Rod Cutting (dp[i] = max(price[j]+dp[i-j]) for all j).', keywords: ['dynamic programming', 'dp', 'memoization', 'tabulation', 'fibonacci', 'coin change', 'lis'], pageRef: 'DSA.pdf p.66-75' },
    { id: 'dsa-9', subject: 'Data Structures & Algorithms', module: 'Dynamic Programming', topic: '2D DP', title: 'Dynamic Programming: 2D Problems', content: '2D DP uses dp[i][j] tables for two-dimensional subproblems. Longest Common Subsequence (LCS): dp[i][j] = dp[i-1][j-1]+1 if match, else max(dp[i-1][j], dp[i][j-1]). O(mn) time and space. Edit Distance (Levenshtein): dp[i][j] = min(insert, delete, replace), O(mn). Matrix Chain Multiplication: dp[i][j] = min(dp[i][k]+dp[k+1][j]+dim multiplication) for all k, O(n³). Unique Paths in grid: dp[i][j] = dp[i-1][j]+dp[i][j-1]. Minimum Path Sum: dp[i][j] = grid[i][j]+min(dp[i-1][j], dp[i][j-1]). Space optimization: often only 2 rows needed.', keywords: ['2d dp', 'lcs', 'edit distance', 'matrix chain', 'grid paths', 'subsequence'], pageRef: 'DSA.pdf p.76-85' },
    { id: 'dsa-10', subject: 'Data Structures & Algorithms', module: 'Dynamic Programming', topic: 'Knapsack', title: 'Knapsack Problems', content: '0/1 Knapsack: items cannot be split. dp[i][w] = max(dp[i-1][w], dp[i-1][w-wt[i]]+val[i]). Time O(nW), space optimizable to O(W). Fractional Knapsack: greedy, sort by value/weight ratio, O(n log n). Unbounded Knapsack: items can be reused. dp[w] = max(dp[w], dp[w-wt[i]]+val[i]). Subset Sum: dp[i][j] = dp[i-1][j] OR dp[i-1][j-nums[i]]. Partition Equal Subset Sum: find if subset sums to total/2. Count of Subsets with Given Sum. Multi-dimensional Knapsack: multiple constraints.', keywords: ['knapsack', '0/1', 'fractional', 'unbounded', 'subset sum', 'partition', 'dp'], pageRef: 'DSA.pdf p.86-92' },
    { id: 'dsa-11', subject: 'Data Structures & Algorithms', module: 'Sorting & Searching', topic: 'Sorting Algorithms', title: 'Sorting Algorithms Comparison', content: 'Comparison-based sorts have Ω(n log n) lower bound. Bubble Sort: O(n²), stable, swap adjacent. Selection Sort: O(n²), unstable, find minimum. Insertion Sort: O(n²), stable, good for nearly sorted, O(n) best case. Merge Sort: O(n log n) always, stable, O(n) extra space, divide and merge. Quick Sort: O(n log n) average, O(n²) worst, unstable, in-place, choose pivot and partition. Heap Sort: O(n log n), unstable, in-place, uses max-heap. Non-comparison: Counting Sort O(n+k), Radix Sort O(d(n+k)), Bucket Sort O(n+k) average — all linear under constraints.', keywords: ['sorting', 'quicksort', 'mergesort', 'heapsort', 'bubble', 'insertion', 'radix', 'stable'], pageRef: 'DSA.pdf p.93-105' },
    { id: 'dsa-12', subject: 'Data Structures & Algorithms', module: 'Sorting & Searching', topic: 'Binary Search', title: 'Binary Search and Variants', content: 'Binary search finds target in O(log n) on sorted arrays. Standard: left=0, right=n-1, mid=(left+right)/2, compare and halve search space. Variants: lower bound (first occurrence), upper bound (last occurrence), search in rotated sorted array, peak element, square root, capacity to ship packages. Binary search on answer: when answer has monotonic property, binary search over result space. Template: while left <= right, check if mid satisfies condition, adjust bounds. Common mistake: integer overflow with (left+right)/2 — use left+(right-left)/2.', keywords: ['binary search', 'lower bound', 'upper bound', 'rotated array', 'search on answer'], pageRef: 'DSA.pdf p.106-112' },
    { id: 'dsa-13', subject: 'Data Structures & Algorithms', module: 'Linked Lists & Stacks', topic: 'Linked Lists', title: 'Linked List Operations and Patterns', content: 'Singly linked list: each node has data + next pointer. Insert at head O(1), at tail O(n) without tail pointer. Detect cycle using Floyd (slow/fast pointers). Reverse: iteratively with three pointers (prev, curr, next). Find middle: slow/fast pointers. Merge two sorted lists: compare heads, pick smaller. Doubly linked list: prev + next pointers, enables O(1) deletion with node reference. Used in LRU Cache with hash map. Skip list: probabilistic structure with multiple levels for O(log n) search.', keywords: ['linked list', 'singly', 'doubly', 'cycle', 'reverse', 'floyd', 'merge', 'lru'], pageRef: 'DSA.pdf p.113-120' },
    { id: 'dsa-14', subject: 'Data Structures & Algorithms', module: 'Linked Lists & Stacks', topic: 'Stacks & Queues', title: 'Stacks, Queues and Applications', content: 'Stack: LIFO, push/pop O(1). Applications: function call management (call stack), undo history, parentheses matching, evaluate postfix expressions, next greater element (monotonic stack), DFS implementation. Queue: FIFO, enqueue/dequeue O(1). Applications: BFS, CPU scheduling, print queue. Priority Queue (heap): insert O(log n), extract-min/max O(log n). Deque: double-ended queue, insert/delete at both ends O(1). Monotonic stack: elements in increasing/decreasing order for efficient range queries. Circular queue: wraps around using modulo.', keywords: ['stack', 'queue', 'lifo', 'fifo', 'priority queue', 'heap', 'monotonic', 'deque'], pageRef: 'DSA.pdf p.121-130' },
    // Database Systems
    { id: 'db-1', subject: 'Database Systems', module: 'SQL', topic: 'SELECT Queries', title: 'SQL SELECT and Filtering', content: 'SELECT retrieves data: SELECT columns FROM table WHERE condition ORDER BY column ASC/DESC LIMIT n. Operators: =, <>, <, >, <=, >=, BETWEEN, IN, LIKE (% wildcard, _ single char), IS NULL. Logical: AND, OR, NOT. DISTINCT removes duplicates. Execution order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. Aliases: AS for column/table renaming. CASE WHEN for conditional logic. String functions: LENGTH, UPPER, LOWER, SUBSTR, CONCAT, TRIM. NULL handling: IS NULL, COALESCE, NULLIF, IFNULL.', keywords: ['select', 'where', 'filter', 'distinct', 'like', 'order by', 'sql basics'], pageRef: 'DBMS.pdf p.1-10' },
    { id: 'db-2', subject: 'Database Systems', module: 'SQL', topic: 'Joins', title: 'SQL Joins and Combining Tables', content: 'INNER JOIN: matching rows from both tables. LEFT OUTER JOIN: all left rows + matching right (NULL for unmatched). RIGHT OUTER JOIN: all right rows + matching left. FULL OUTER JOIN: all rows from both tables. CROSS JOIN: Cartesian product (m×n rows). SELF JOIN: table joined with itself (e.g., employee-manager). NATURAL JOIN: automatic join on common column names. Join conditions: ON clause (explicit), USING clause (shared column name). Performance: joins benefit from indexes on join columns. Multiple joins: chain them sequentially.', keywords: ['join', 'inner', 'left', 'right', 'full', 'cross', 'self', 'natural', 'outer'], pageRef: 'DBMS.pdf p.11-18' },
    { id: 'db-3', subject: 'Database Systems', module: 'SQL', topic: 'Subqueries', title: 'Subqueries and Nested Queries', content: 'Subquery: query nested inside another. Types: Scalar (returns single value), Row (single row), Table (set of rows). Usage in: WHERE (WHERE column IN (SELECT...)), FROM (derived table), SELECT (scalar subquery), HAVING. Correlated subquery: references outer query, executes per outer row. EXISTS: checks if subquery returns any rows. NOT EXISTS: opposite. ANY/ALL with comparison operators. Common patterns: find max/min with subquery, find duplicates, find rows with no match (anti-join). CTEs (WITH clause): Named subqueries for readability and recursion.', keywords: ['subquery', 'nested', 'correlated', 'exists', 'cte', 'with', 'scalar', 'derived table'], pageRef: 'DBMS.pdf p.19-25' },
    { id: 'db-4', subject: 'Database Systems', module: 'SQL', topic: 'Aggregation', title: 'SQL Aggregation and Grouping', content: 'Aggregate functions: COUNT(*) counts all rows, COUNT(col) counts non-null, SUM, AVG, MIN, MAX — applied to groups. GROUP BY groups rows by column values. HAVING filters groups after aggregation (vs WHERE which filters rows before). Examples: average salary per department, count students per grade, max score per subject. Multiple GROUP BY columns create combined groups. GROUP BY with ROLLUP/CUBE for subtotals. GROUPING function identifies summary rows. Window functions: ROW_NUMBER, RANK, DENSE_RANK, NTILE OVER (PARTITION BY... ORDER BY...) for analytics without reducing rows.', keywords: ['aggregate', 'group by', 'having', 'count', 'sum', 'avg', 'window function', 'rank'], pageRef: 'DBMS.pdf p.26-33' },
    { id: 'db-5', subject: 'Database Systems', module: 'Normalization', topic: '1NF 2NF 3NF', title: 'Database Normalization: 1NF, 2NF, 3NF', content: 'Normalization eliminates redundancy and update anomalies. 1NF: atomic values, no repeating groups, each row unique. Example violation: multi-valued columns like "Phone: 123, 456". 2NF: 1NF + no partial dependencies — every non-key attribute depends on the entire candidate key (relevant when composite key exists). Example: OrderItems(OrderID, ProductID, ProductName) violates 2NF because ProductName depends only on ProductID. 3NF: 2NF + no transitive dependencies — non-key attribute should not depend on another non-key attribute. Example: Student(ID, Dept, DeptHead) violates 3NF because DeptHead depends on Dept transitively.', keywords: ['normalization', '1nf', '2nf', '3nf', 'partial dependency', 'transitive', 'atomic', 'anomaly'], pageRef: 'DBMS.pdf p.34 - 42' },
    { id: 'db-6', subject: 'Database Systems', module: 'Normalization', topic: 'BCNF', title: 'Boyce-Codd Normal Form', content: 'BCNF (3.5NF): for every functional dependency X→Y, X must be a superkey. Stricter than 3NF — 3NF allows non-superkey determinants if the dependent is part of a candidate key. Decomposition into BCNF: identify violating FD X→Y, decompose R into R1(X,Y) and R2(R-Y). BCNF decomposition always achieves lossless join but may not preserve all FDs. Example: Teach(Student, Course, Instructor) with FDs: {Student,Course}→Instructor and Instructor→Course. Instructor→Course violates BCNF since Instructor is not a superkey.', keywords: ['bcnf', 'superkey', 'decomposition', 'lossless', 'functional dependency', 'boyce-codd'], pageRef: 'DBMS.pdf p.43-48' },
    { id: 'db-7', subject: 'Database Systems', module: 'Normalization', topic: 'Functional Dependencies', title: 'Functional Dependencies and Armstrong Axioms', content: 'Functional dependency X→Y: Y is uniquely determined by X. Armstrong Axioms: 1) Reflexivity: if Y⊆X then X→Y, 2) Augmentation: if X→Y then XZ→YZ for any Z, 3) Transitivity: if X→Y and Y→Z then X→Z. Derived rules: Union (X→Y, X→Z ⟹ X→YZ), Decomposition (X→YZ ⟹ X→Y, X→Z), Pseudotransitivity (X→Y, WY→Z ⟹ XW→Z). Closure of attributes X⁺: all attributes determined by X using given FDs. Candidate key: minimal set of attributes whose closure is all attributes. Finding candidate keys: start with attributes not on RHS of any FD.', keywords: ['functional dependency', 'armstrong', 'closure', 'candidate key', 'superkey', 'axioms'], pageRef: 'DBMS.pdf p.49-55' },
    { id: 'db-8', subject: 'Database Systems', module: 'Transactions', topic: 'ACID Properties', title: 'Transaction ACID Properties', content: 'Transaction: logical unit of work with ACID properties. Atomicity: all-or-nothing execution, ensured by undo log (rollback incomplete transactions). Consistency: transaction takes DB from one valid state to another, enforced by constraints (primary key, foreign key, check). Isolation: concurrent transactions do not interfere, controlled by isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable). Durability: committed changes survive crashes, ensured by redo log (write-ahead logging - WAL). Transaction states: Active → Partially Committed → Committed or Failed → Aborted.', keywords: ['acid', 'atomicity', 'consistency', 'isolation', 'durability', 'transaction', 'wal', 'log'], pageRef: 'DBMS.pdf p.56-63' },
    { id: 'db-9', subject: 'Database Systems', module: 'Transactions', topic: 'Concurrency Control', title: 'Concurrency Control Mechanisms', content: 'Concurrency problems: Lost Update (two writes, one overwritten), Dirty Read (reading uncommitted data), Non-repeatable Read (re-read gives different value), Phantom Read (new rows appear). Solutions: Lock-based: Shared (read) and Exclusive (write) locks. Two-Phase Locking (2PL): Growing phase (acquire locks), Shrinking phase (release locks) — ensures serializability. Strict 2PL holds all exclusive locks until commit. Timestamp-based: older transaction gets priority (Wait-Die: older waits, younger dies; Wound-Wait: older wounds, younger waits). MVCC (Multi-Version Concurrency Control): readers see snapshot, writers create new version.', keywords: ['concurrency', 'lock', '2pl', 'timestamp', 'mvcc', 'dirty read', 'lost update', 'phantom'], pageRef: 'DBMS.pdf p.64-72' },
    { id: 'db-10', subject: 'Database Systems', module: 'Transactions', topic: 'Deadlocks', title: 'Deadlock Detection and Prevention', content: 'Deadlock: circular wait where transactions hold locks needed by others. Conditions (all must hold): Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait. Detection: Wait-For Graph — if cycle exists, deadlock detected. Resolution: abort youngest/least-work transaction (victim selection). Prevention: Wound-Wait (older wounds younger, younger waits for older), Wait-Die (older waits for younger, younger dies for older). Timeout-based: abort transaction waiting too long. Deadlock avoidance: order resources, acquire all locks at once. Starvation prevention: priority aging.', keywords: ['deadlock', 'wait-for graph', 'wound-wait', 'wait-die', 'prevention', 'detection', 'cycle'], pageRef: 'DBMS.pdf p.73-78' },
    { id: 'db-11', subject: 'Database Systems', module: 'Indexing & Storage', topic: 'B+ Trees', title: 'B+ Tree Indexing', content: 'B+ Tree: balanced tree structure for database indexing. Order m: each node has m/2 to m children (except root). Internal nodes store keys for routing; leaf nodes store actual data pointers and are linked sequentially. Search O(log_m n), Insert O(log_m n) with possible node split, Delete O(log_m n) with possible merge/redistribute. Example: order 4 means max 3 keys, max 4 children per node. Dense index: entry for every search key value. Sparse index: entry for every block. Clustered index: data physically ordered by index. Non-clustered: separate from data ordering. B+ Tree advantages: balanced height, excellent for range queries via linked leaves.', keywords: ['b+ tree', 'index', 'order', 'leaf', 'internal', 'clustered', 'non-clustered', 'dense', 'sparse'], pageRef: 'DBMS.pdf p.79-88' },
    { id: 'db-12', subject: 'Database Systems', module: 'Indexing & Storage', topic: 'Hashing', title: 'Hash-Based Indexing', content: 'Hash function maps search key to bucket address. Static hashing: fixed number of buckets, overflow chains for collisions. h(k) = k mod B where B is number of buckets. Problems: bucket overflow, poor distribution. Dynamic hashing: grows/shrinks with data. Extendible hashing: uses directory of pointers, doubles directory on overflow, splits only one bucket. Linear hashing: splits buckets one by one in round-robin order, no directory needed. Hash index is excellent for equality queries O(1) average, but poor for range queries. Bitmap index: for low-cardinality attributes, uses bit vectors per value.', keywords: ['hashing', 'bucket', 'overflow', 'extendible', 'linear', 'hash function', 'bitmap'], pageRef: 'DBMS.pdf p.89-95' },
    { id: 'db-13', subject: 'Database Systems', module: 'ER Modeling', topic: 'ER Diagrams', title: 'Entity-Relationship Modeling', content: 'ER Model represents real-world structure. Entity: object/thing (rectangle). Attribute: property of entity (oval). Key attribute: uniquely identifies entity (underlined). Relationship: association between entities (diamond). Cardinality: 1:1, 1:N, M:N. Participation: total (double line, every entity participates) or partial (single line). Weak entity: cannot exist without identifying strong entity (double rectangle), has discriminator (partial key). Generalization/Specialization: ISA hierarchy (triangle), overlapping/disjoint, total/partial. Converting ER to relational: entity→table, 1:1 merge or FK, 1:N FK on N-side, M:N separate junction table.', keywords: ['er diagram', 'entity', 'relationship', 'cardinality', 'weak entity', 'generalization', 'participation'], pageRef: 'DBMS.pdf p.96-105' },
    { id: 'db-14', subject: 'Database Systems', module: 'ER Modeling', topic: 'Relational Algebra', title: 'Relational Algebra Operations', content: 'Relational algebra: procedural query language for relational model. Fundamental operations (5): 1) Selection σ: filter rows by condition, 2) Projection π: select columns, 3) Union ∪: combine compatible relations, 4) Set Difference -: rows in R but not S, 5) Cartesian Product ×: combine all row pairs. Derived operations: Intersection R∩S = R-(R-S), Natural Join ⋈: Cartesian product + select on common attributes + project to remove duplicates, Division R÷S: tuples in R associated with all tuples in S. Theta join: join with arbitrary condition. Semijoin: R ⋉ S = π_A(R ⋈ S). Rename ρ: rename relation or attributes.', keywords: ['relational algebra', 'selection', 'projection', 'union', 'join', 'cartesian', 'division', 'sigma', 'pi'], pageRef: 'DBMS.pdf p.106-115' },
];

// Initialize vocabulary on import
buildVocabulary(knowledgeBase);

// Pre-compute vectors
const chunkVectors = knowledgeBase.map(chunk => ({
    chunk,
    vector: textToVector(`${chunk.title} ${chunk.content} ${chunk.keywords.join(' ')}`),
}));

// --- Subject Code Mapping ---
const subjectCodeMap: Record<string, string> = {
    'ml': 'machine learning',
    'dsa': 'data structures',
    'db': 'database',
    'machine learning': 'machine learning',
    'data structures & algorithms': 'data structures',
    'database systems': 'database',
};

function resolveSubject(code: string): string {
    return subjectCodeMap[code.toLowerCase()] || code.toLowerCase();
}

// --- Public API ---
export function searchKnowledge(
    query: string,
    options?: { subject?: string; topK?: number; minScore?: number }
): Array<{ chunk: KnowledgeChunk; score: number }> {
    const topK = options?.topK ?? 3;
    const minScore = options?.minScore ?? 0.05;

    const queryVector = textToVector(query);

    let results = chunkVectors.map(({ chunk, vector }) => ({
        chunk,
        score: cosineSimilarity(queryVector, vector),
    }));

    // Filter by subject if specified (supports both short codes like 'ML' and full names)
    if (options?.subject) {
        const resolvedSubject = resolveSubject(options.subject);
        results = results.filter(
            r => r.chunk.subject.toLowerCase().includes(resolvedSubject) ||
                r.chunk.module.toLowerCase().includes(resolvedSubject)
        );
    }

    // Sort by score descending, filter by minimum, take topK
    return results
        .filter(r => r.score >= minScore)
        .sort((a, b) => b.score - a.score)
        .slice(0, topK);
}

export function getKnowledgeForTopic(subject: string, topic: string): KnowledgeChunk | undefined {
    return knowledgeBase.find(
        k => k.subject.toLowerCase().includes(subject.toLowerCase()) &&
            k.topic.toLowerCase().includes(topic.toLowerCase())
    );
}

export function getAllKnowledgeChunks(): KnowledgeChunk[] {
    return knowledgeBase;
}

export function getKnowledgeBySubject(subject: string): KnowledgeChunk[] {
    return knowledgeBase.filter(
        k => k.subject.toLowerCase().includes(subject.toLowerCase())
    );
}
